### ISSUE TITLE
CMUX中AT指令与PPP两通道同时使用情况下，中途拆除SIM卡，出现内存访问越界导致死机

### ISSUE THREAD

**Issue by lizhen9880** [RT-Thread-packages/cmux#4]
### 开发环境
 - STM32F429
 - RAM 32MB(EXT)
 - ROM 1MB
 - EC20 4G模组
 - keil MDK
 - Windows
 - 软件包：cmux,at_client,ppp
 ### 操作流程及现象 
 - 开机后启动CMUX
 - 在 cmux.at 通道上注册EC20设备（只初始化，不注册为网络设备。这一点对实验结果无影响）
 - 启动PPP
 - ping baidu.com 成功
 - 手动拿掉SIM卡，5-10s后收到AT通道发出的:
   - +CPIN: NOT READY
   - +QIURC: "pdpdeact",1
 - 发生内存访问越界，命令行中会打印出大量字符串，目测是flash中内容，然后死机
 ### 追踪
追踪了一下LR寄存器中的定位，在接收到+QIURC: "pdpdeact",1之后 [cmux.c-L972处](https://github.com/RT-Thread-packages/cmux/blob/master/src/cmux.c#L972) data指针指向地址异常，至于是什么原因导致了此异常，劳烦熟悉cmux软件架构的维护人员分析下了

**Comment by xiangxistu** [comment]
通过 ```cmux_vcom_read```读取数据时，会根据用户提供的 buffer 大小选择不同的拷贝策略；
只有对于一个巨大的一条数据而言，才会用到 [cmux.c-L972处](https://github.com/RT-Thread-packages/cmux/blob/master/src/cmux.c#L972)的策略；出现这个情况的原因就是在接收时收到巨大的 cmux_frame 。


可以烦请验证该问题，在 [cmux.c-L938处](https://github.com/RT-Thread-packages/cmux/blob/ddab8a586dad99209f8ecac1746ab27c540dcd58/src/cmux.c#L938)添加 ```LOG_D("len: %d.", frame->data_length``` 验证该问题。

**Comment by lizhen9880** [comment]
![image](https://user-images.githubusercontent.com/3376530/90222523-cbfe4a00-de3e-11ea-8471-208cf5e79d80.png)
