### ISSUE TITLE
CMUX should allow user to decide the physical UART TX method.

### ISSUE THREAD

**Issue by majianjia** [RT-Thread-packages/cmux#9]
https://github.com/RT-Thread-packages/cmux/blob/c00d7695632716a03f95f4b5398e86142929e4be/src/gsm/cmux_gsm.c#L51

The default UART TX method is polling. But users might want to use INT or DMA. 
The TX should configurable by the user.

**Comment by armink** [comment]
后面用串口 V2 框架后就不会有这个问题了
